config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show]

  resources :restaurants, only: [:show]
  resources :dishes, only: [:index]


  resources :dishes, only: [:show, :destroy] do
    resources :votes, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end

  get 'dishes/:dish_id/favorites/toggle', to: 'favorites#toggle', as: :toggle

  resources :reviews, only: [:show] do
    resources :vote_reviews, only: [:create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include AlgoliaSearch
  has_many :dishes

  algoliasearch do
    attributes :name
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  include AlgoliaSearch

  belongs_to :restaurant
  belongs_to :category

  has_many :votes, dependent: :destroy
  has_many :votants, through: :votes
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  algoliasearch do
    attributes :name
    add_attribute :category_name
  end

  def category_name
    # self.category.name
    category.name
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :dish
  belongs_to :user

  validates :dish, uniqueness: { scope: :user }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dishes, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :dish
  has_many :vote_reviews, dependent: :destroy

  def date
    min_date = Time.now - 4.years
    max_date = Time.now - 0.year
    rand(min_date..max_date).to_s[0..9]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :liked_dishes, through: :votes
  has_many :vote_reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :dish
  belongs_to :user

  enum selectable_vote: [:upvote, :downvote]
end

app/models/vote_review.rb
class VoteReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :photo ])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index

    @category = Category.find_by("name ILIKE ?", "%#{params[:category]}%") # Japansese
    @dishes = @category.dishes # not array
    @list = @dishes.sort_by { |dish| -total_dish_votes(dish) } # array


    @other_categories = Category.where.not(id: @category.id) # [ Canadain, Korean ]
    @other_dishes = other_cat # array
    @other_list = @other_dishes.sort_by { |dish| -total_dish_votes(dish) } # array of arrayt

    # @other_list = other_cat.sort_by { |dish| -total_dish_votes(dish) }

    @addresses = selected_addresses
    @restaurant_addresses = @addresses.geocoded
    @markers = @restaurant_addresses.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude
        # infoWindow: render_to_string(partial: "info_window", locals: { product: product })
      }
    end
  end

  def selected_addresses
    Restaurant.joins(:dishes).where(dishes: { id: @dishes }).distinct
  end

# -------------------------------------------------------------------------------
  def other_cat
    @other_categories.map(&:dishes).flatten(1)
  end

  def total_votes
    @dishes.map do |dish|
      total_dish_votes(dish)
    end
  end

  def total_dish_votes(dish)
    dish.votes.map {|votes| votes.vote }.sum
  end

  # def other_list_order
  #   list = @other_dishes.map { |dish| dish }
  #   list == @other_dishes
  # end

  # def list_order # transfer Hash to Array
  #   list = []
  #   @dishes.each do |dish|
  #     list << dish
  #   end
  #   return list
  # end
#-------------------------------------------------------------------------------
  def show
    @dish = Dish.find(params[:id])
    @list = list_review_order.sort_by { |v| -total_review_votes(v) }
  end

  def list_review_order
    list = []
    @dish.reviews.each do |review|
      list << review
    end
    return list
  end

  def total_review_votes(review)
    review.vote_reviews.map {|votes| votes.vote }.sum
  end

  def destroy
    @dish = Dish.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new
    @dish = Dish.find(params[:dish_id])
    @favorite.user = current_user
    @favorite.dish = @dish

    @favorite.save

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    
    @dish = @favorite.dish # we need `dish.id` to identify which cards to remove in the DOM.
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!
  layout "landing"

  def home
    @dishes = Dish.all
    @categories = Category.all
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
    @votes = total_votes.sum
    @list = list_order.sort_by { |v| -total_dish_votes(v) }
    qrcode = RQRCode::QRCode.new("http://github.com/")
    @svg_string = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
  end



  def total_votes
    votes = []
    @restaurant.dishes.each do |dish|
      votes << total_dish_votes(dish)
    end
    return votes
  end

  def total_dish_votes(dish)
    dish.votes.map {|votes| votes.vote }.sum
  end

  def list_order
    list = []
    @restaurant.dishes.each do |dish|
      list << dish
    end
    return list
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @reviews = current_user.reviews
  end
end

app/controllers/vote_reviews_controller.rb
class VoteReviewsController < ApplicationController
  def create
    @vote_review = VoteReview.new
    @review = Review.find(params[:review_id])
    @vote_review.user = current_user
    @vote_review.review = @review
    @vote_review.vote = params[:vote].to_i
    @vote_review.save

    if @vote_review.vote > 0
      @upvote = true
    else
      @upvote = false
    end


    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js  # <-- will render `app/views/votes/create.js.erb`
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.new
    @dish = Dish.find(params[:dish_id])
    @vote.user = current_user
    @vote.dish = @dish
    @vote.vote = params[:vote].to_i
    @vote.save

    if @vote.vote > 0
      @upvote = true
    else
      @upvote = false
    end


    respond_to do |format|
      format.html { redirect_to dish_path(@dish) }
      format.js  # <-- will render `app/views/votes/create.js.erb`
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("https") ? meta_image : image_url(meta_image)
  end
end

app/views/dishes/show.html.erb
<style>
  .link-to-text-color-ajax-icon {
    .color: red!important;
  }
</style>
<div class="head-container">
  <div class="mobile-forehead">
    <img src="<%= @dish.photo %>" alt="dish photo", width="100px" class="food_photo">

      <div class="text_area">

        <h1>
          <%= @dish.name %>
          <% if !user_signed_in? || current_user.favorites.filter { |favorite| favorite.dish == @dish}.empty? %>
              <%= link_to '<i class="far fa-heart"></i>'.html_safe, dish_favorites_path(@dish), method: :post, remote: true, class: "unfavorited-heart-icon-dish-id-#{@dish.id} show-link-to-text-color" %>
          <% else %>
              <%= link_to '<i class="fas fa-heart"></i>'.html_safe, dish_favorite_path(@dish, current_user.favorites.filter { |favorite| favorite.dish == @dish}.first ), method: :delete, class: 'show-link-to-text-color-liked', remote: true, class: "show-link-to-text-color favorited-heart-icon-dish-id-#{@dish.id}" %>
          <% end %>
        </h1>


        <span>
          <%= link_to @dish.restaurant.name, restaurant_path(@dish.restaurant) %>
        </span>
      </div>
  </div>

  <div class="review-container">
    <div class="vote-container">
      <%= link_to '<i class="fas fa-thumbs-down"></i>'.html_safe , dish_votes_path(@dish, vote: -1), method: :post, class: "vote-button down", remote: true%>
      <div class="num_box">
        <h1 id="total-dish-votes"><%= @dish.votes.map{|vote| vote.vote}.sum %></h1>
        <p> votes </p>
      </div>
      <%= link_to '<i class="fas fa-thumbs-up"></i>'.html_safe, dish_votes_path(@dish, vote: 1), method: :post, class: "vote-button up", remote: true%>
    </div>

    <h5 class="add-review">Add Reviews</h5>
    <% @list.each do |review| %>
      <div class="review-card">

        <div class="review-vote-area">
          <span><%= link_to '<i class="fas fa-chevron-up fa-lg"></i>'.html_safe, review_vote_reviews_path(review, vote: 1), method: :post, class: "review-button up", remote: true %></span>
          <span id="total-review-votes-<%= review.id %>"><%= review.vote_reviews.map{|vote| vote.vote}.sum %></span>
          <span><%= link_to '<i class="fas fa-chevron-down fa-lg"></i>'.html_safe, review_vote_reviews_path(review, vote: -1), method: :post, class: "review-button down", remote: true %></span>
        </div>
        
        <%= link_to user_path(User.last) do %>
          <img src="<%= review.user.photo %>" alt="avatar", width="25px" class="avatar">
        <% end %>
        <div class="review-text-area">
          <div class="review-title">
            <h3><%= review.user.username%></h3>
            <p><%= review.date%></p>
          </div>

          <% unless review.photo.nil?%>
            <img src="<%= review.photo %>" class = " review-photo" alt="review photo", width="25px">
          <% end %>

          <div class="review-body">
            <% if review.content.length > 120 %>
              <p><%= review.content.split(" ")[0...22].join(" ")%><span class="dots">...</span><span class="more" style="display:none;"><%= review.content.split(" ")[22..-1].join(" ") %></span></p>
              <div class="myBtn">Read more</div></p>
            <% else %>
              <p><%= review.content %></p>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="background-container">

  <div id="video-overlay"></div>
  <video id="mainVideo" autoplay muted loop src="<%= asset_path 'video (2).mp4'%>"></video>

  <div class="container" style="display: flex; flex-direction: column;">

    <div style="position: relative; width: 400px; align-self:center;" class="title d-flex justify-content-center">
      <h1 class="homepage-logo">Cravings</h1>
      <svg style="position: absolute; right: 16%;" width="24" height="35" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="6" cy="6" r="6" fill="#FFFDFD"/>
        <circle cx="6" cy="6" r="4" fill="#FD5C3A"/>
      </svg>
    </div>

    <%= form_tag dishes_path, id: "index_form", method: :get do %>
      <div class="searchbutton d-flex justify-content-center" style="position: relative;">
        <%= text_field_tag :category,
          params[:category],
          class: 'searchbar index_search',
          id: 'banner-typed-text',
          value: '',
          style: 'width: 65%;'
        %>
        <%= submit_tag ">", id: "index_submit", class: 'btn btn-primary', style: "border: none; width: 35px; height: 35px; border-radius: 100%; position: absolute; right: 20%; top: -26%;"%>
      </div>
    <% end %>

    <div id="hidden_search_area">
      <div id="search_result_category">
        <% @categories.each do |category| %>
          <%= link_to dishes_path(category: category.name) do %>
            <div class="card-trip-link" style="display: none;" id="category-<%= category.id %>">
              <strong><%= category.name %></strong>
            </div>
          <% end %>
        <% end %>
      </div>

      <div id="search_result_dishes">
        <% @dishes.each do |dish| %>
          <%= link_to dishes_path(dish: dish.name) do %>
            <div class="card-trip-link" style="display: none;" id="dish-<%= dish.id %>">
              <%= dish.name %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="moving-input">
      <p><span id="banner-typed-text"></span></p>
    </div>

  </div>

</div>

app/views/restaurants/show.html.erb
<!-- Coupon Area -->

<div id="popup1" class="overlay">
  <div class="popup">
    <a class="close" href="#">&times;</a>
    <div class="content">
      <h3>15% OFF</h3>
      <p>Congrats! You get coupon for your next visit to <strong style="color: $main-orange;"><%= @restaurant.name %></strong></p>
      <img id="coupon-gif" src="https://item.kakaocdn.net/do/36e509cee3c0d3e6284e26f4df760bcaf43ad912ad8dd55b04db6a64cddaf76d" alt="Celebrate" style="width: 50%;">
    </div>
    <div class="qrcode">
      <svg>
        <%= @svg_string.html_safe %>
      </svg>
    </div>
  </div>
</div>

<div class="coupon-popup"  id="redeem">
  <div class="coupon-line">
    <div class="hooray-text">
      <p id="hooray" style="font-weight: bold;">Hooray!</p>
      <!-- <p id="hooray-notification">We’ve found a coupon for you!</p> -->
      <a>
        Coupon <br> for you :)
      </a>
    </div>
    <div class="hooray-gif">
      <img id="celebrate-gif" src="https://i.pinimg.com/originals/93/94/fb/9394fb96035f3f7c61b885ae8df208c5.gif" alt="Celebrate" style="width:79px;height:84px;">
    </div>
  </div>
</div>


<!--Resto Area -->
<div class="head-container" >
  <div class="mobile-forehead">
    <img src="<%= @restaurant.photo %>" alt="restaurant photo", width="100px" class="restaurant_photo">

    <div class="text_area">
      <h1><%= @restaurant.name %> <i class="fas fa-map-marker-alt"></i></h1>
      <span>
        <%= link_to @restaurant.dishes.first.category.name.capitalize, dishes_path(category: "japanese") %>
      </span>
    </div>
  </div>






  <div class="review-container">
    <div class="vote-container">
      <div class="num_box">
        <h1><%= @votes %></h1>
        <h6>Satisfied cravers</h6>
      </div>
    </div>
    <% @list.each do |dish| %>

      <div class="container_card_lg show dish-card" data-path="/dishes/<%= dish.id %>">

        <div class="card_lg">

          <img src="<%= dish.photo %>" alt="dish photo">

          <div class="flex-grow-1">
            <div class="justify-content-end text-right">
              <span>
              <strong><%= dish.votes.map{|vote| vote.vote}.sum %> <i class="like fas fa-thumbs-up"></i></strong>
              </span>
            </div>
            <div class="card_infos">
              <h2 class="txt"><%= dish.name %></h2>
              <p class="txt_desc"><%= dish.restaurant.name %></p>
            </div>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

<!--
<script>
document.querySelectorAll(".dish-card").forEach((card) => {
  console.log(card)
  card.addEventListener("click", (event) => {
    window.location.href = "http://" + window.location.host + event.currentTarget.getAttribute('data-path');
  })
})
</script>
 -->

app/views/shared/_animated_favorited_dish_card.html.erb
<div class="card animated fadeIn" data-favorite-id="<%= favorite.id %>" data-dish-id="<%= dish.id %>" >
  <img src="<%= favorite.dish.restaurant.photo %>" alt="", class="logo">
<!--               <div class="card_ban d-flex justify-content-end" style="background-image: linear-gradient(rgba(255, 255, 255, 0.25),rgba(255, 255, 255, 0.25)), url(<%= favorite.dish.photo %>);">
-->              <div class="card_ban d-flex justify-content-end" style="background-image: url(<%= favorite.dish.photo %>);">
      <div>
        <% if current_user.favorites.filter { |favorites| favorites.dish == favorite.dish}.empty? %>
          <%= link_to '<i class="far fa-heart"></i>'.html_safe, dish_favorites_path(favorite.dish), class: 'link-to-text-color', method: :post, remote: true %>
        <% else %>
          <%= link_to '<i class="fas fa-heart"></i>'.html_safe, dish_favorite_path(favorite.dish, current_user.favorites.filter { |favorites| favorites.dish == favorite.dish}.first ), class: 'link-to-text-color-liked', method: :delete, remote: true %>
       <% end %>
     </div>
  </div>
<%= link_to dish_path(favorite.dish), class: "link-to-dish" do %>
  <div class="card_detail">
    <div class="vote_num_2 d-flex justify-content-end">
      <span><strong><%= favorite.dish.votes.map{|vote| vote.vote}.sum %></strong></span>
      <i class="fas fa-thumbs-up"></i>
    </div>
    <div class="d-flex flex-column justify-content-between card-content">
      <h4 class="txt"><%= favorite.dish.name %></h4>
      <div class="txt-subtilte d-flex justify-content-between">
        <span class="txt_desc">
          <%= favorite.dish.restaurant.name %>
        </span>
        <span class="txt_desc">
          <%= "$" * (favorite.dish.price) %>
        </span>
      </div>

    </div>
  </div>
<% end %>
</div>

app/views/shared/_favorited_dish_card.html.erb
  <div class="card" data-favorite-id="<%= favorite.id %>" data-dish-id="<%= dish.id %>" >
    <img src="<%= favorite.dish.restaurant.photo %>" alt="", class="logo">
<!--               <div class="card_ban d-flex justify-content-end" style="background-image: linear-gradient(rgba(255, 255, 255, 0.25),rgba(255, 255, 255, 0.25)), url(<%= favorite.dish.photo %>);">
-->              <div class="card_ban d-flex justify-content-end" style="background-image: url(<%= favorite.dish.photo %>);">
        <div>
          <% if current_user.favorites.filter { |favorites| favorites.dish == favorite.dish}.empty? %>
            <%= link_to '<i class="far fa-heart"></i>'.html_safe, dish_favorites_path(favorite.dish), class: 'link-to-text-color', method: :post, remote: true %>
          <% else %>
            <%= link_to '<i class="fas fa-heart"></i>'.html_safe, dish_favorite_path(favorite.dish, current_user.favorites.filter { |favorites| favorites.dish == favorite.dish}.first ), class: 'link-to-text-color-liked', method: :delete, remote: true %>
         <% end %>
       </div>
    </div>
  <%= link_to dish_path(favorite.dish), class: "link-to-dish" do %>
    <div class="card_detail">
      <div class="vote_num_2 d-flex justify-content-end">
        <span><strong><%= favorite.dish.votes.map{|vote| vote.vote}.sum %></strong></span>
        <i class="fas fa-thumbs-up"></i>
      </div>
      <div class="d-flex flex-column justify-content-between card-content">
        <h4 class="txt"><%= favorite.dish.name %></h4>
        <div class="txt-subtilte d-flex justify-content-between">
          <span class="txt_desc">
            <%= favorite.dish.restaurant.name %>
          </span>
          <span class="txt_desc">
            <%= "$" * (favorite.dish.price) %>
          </span>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/shared/_filled_heart_icon.html.erb
<%= link_to '<i class="fas fa-heart"></i>'.html_safe, dish_favorite_path(@dish, current_user.favorites.filter { |favorite| favorite.dish == @dish}.first ), method: :delete, class: 'show-link-to-text-color-liked', remote: true, class: "show-link-to-text-color favorited-heart-icon-dish-id-#{@dish.id}" %>

app/views/shared/_footbar.html.erb
<div class="footbar">
  <%= link_to '<i class="fas fa-utensils fa-lg"></i>'.html_safe, dishes_path(category: "japanese"), class: "footbar_button #{controller_name == 'dishes' ? 'active' : ''}"   %>
  <%= link_to '<i class="fas fa-search fa-lg"></i>'.html_safe, "", class: "footbar_button"  %>
  <%= link_to '<i class="far fa-heart fa-lg"></i>'.html_safe, "", class: "footbar_button"  %>
  <% if user_signed_in? %>
    <%= link_to '<i class="far fa-user fa-lg"></i>'.html_safe, user_path(current_user), class: "footbar_button"  %>
  <% else  %>
    <%= link_to '<i class="far fa-user fa-lg"></i>'.html_safe, new_user_session_path, class: "footbar_button #{controller_name == 'users' ? 'active' : ''}"  %>
  <% end %>

  <span class="footbar_button dropup">
    <button class="dropbtn">
      <i class="fas fa-bars fa-lg"></i>
    </button>
  </span>
</div>


<div class="dropup-content">
  <% if user_signed_in? %>
    <%= link_to '<i class="fas fa-power-off"></i><span>  Sign out</span>'.html_safe, destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  <% else %>
    <%= link_to '<i class="fas fa-power-off"></i><span>  Sign in</span>'.html_safe, new_user_session_path, class: "nav-link" %>
    <%= link_to '<i class="fas fa-user-plus"></i><span>  New user</span>'.html_safe, new_user_registration_path, class: "nav-link" %>
  <% end %>
  <a href="#"><i class="far fa-envelope"></i><span>  Contact us</span></a>
  <a href="#"><i class="fas fa-cog"></i><span>  Setting</span></a>
</div>

app/views/shared/_navbar.html.erb
<nav role="navigation">
  <div id="menuToggle">

    <input type="checkbox" id="navbar-toggle-btn" />
    <span></span>
    <span></span>
    <span></span>

    <ul id="menu">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, :gravity=>"face", :width=>50, :height=>50, :crop=>"thumb" %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My page ", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Add Product", new_product_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
      <a href="#"><li>Home</li></a>
      <a href="#"><li>About</li></a>
      <a href="#"><li>Info</li></a>
      <a href="#"><li>Contact</li></a>
    </ul>
  </div>
</nav>
<!-- <div style="height: 30px;"> </div> -->



<nav class="navbar">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, :gravity=>"face", :width=>50, :height=>50, :crop=>"thumb" %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My page ", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Add Product", new_product_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>
 -->

app/views/shared/_unfavorited_dish_card.html.erb
<div class="card main_dish_search_card" data-description="<%= dish.name %>" data-dish-id="<%= dish.id %>">
  <img src="<%= dish.restaurant.photo %>" alt="", class="logo">
  <!-- <div class="card_ban d-flex justify-content-end" style="background-image: linear-gradient(rgba(255, 255, 255, 0.25),rgba(255, 255, 255, 0.25)), url(<%= dish.photo %>);"> -->
  <div class="card_ban d-flex justify-content-end" style="background-image: url(<%= dish.photo %>);">
    <div>
      <% if !user_signed_in? || current_user.favorites.filter { |favorite| favorite.dish == dish}.empty? %>
        <%= link_to '<i class="far fa-heart"></i>'.html_safe, dish_favorites_path(dish), class: 'link-to-text-color', method: :post, remote: true %>
      <% else %>
        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, dish_favorite_path(dish, current_user.favorites.filter { |favorite| favorite.dish == dish}.first ), class: 'link-to-text-color-liked', method: :delete, remote: true %>
      <% end %>
    </div>
  </div>
  <%= link_to dish_path(dish), class: "link-to-dish" do %>
    <div class="card_detail">
      <div class="vote-num d-flex justify-content-end">
        <span><strong><%= dish.votes.map{|vote| vote.vote}.sum %></strong></span>
        <i class="fas fa-thumbs-up"></i>
      </div>
      <div class="card-content d-flex flex-column justify-content-between">
        <h4 class="txt"><%= dish.name %></h4>
        <div class="txt-subtilte d-flex justify-content-between">
          <span class="txt_desc">
            <%= dish.restaurant.name %>
          </span>
          <span class="txt_desc">
            <%= "$" * (dish.price) %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_unfilled_heart_icon.html.erb
<%= link_to '<i class="far fa-heart"></i>'.html_safe, dish_favorites_path(@dish), method: :post, remote: true, class: "unfavorited-heart-icon-dish-id-#{@dish.id} show-link-to-text-color" %>